# Generated by Django 5.1.4 on 2025-01-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='gateways',
            field=models.ManyToManyField(blank=True, null=True, to='payments.gateway'),
        ),
    ]
